// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8088/api/v1' | (string & {});
};

export type ErrorResponse = {
    error: string;
    message: string;
};

export type ElementType = 'requirement' | 'feature' | 'task' | 'bug' | 'evaluation' | 'risk';

export type TaskStatus = 'backlog' | 'todo' | 'in_progress' | 'in_review' | 'testing' | 'blocked' | 'done' | 'rejected';

export type LinkType = 'related' | 'child' | 'implement';

export type AccessLevel = 'read' | 'write' | 'admin';

export type FieldType = 'string' | 'textarea' | 'integer' | 'real' | 'choice';

export type Project = {
    project_identifier: string;
    project_name: string;
    project_description?: string;
    /**
     * Unix-style slash-delimited path used to organise projects into a multi-depth folder tree, e.g. "engineering/firmware/sensors". An empty string means the project sits at the root. Split on "/" in the GUI to reconstruct tree nodes.
     *
     */
    folder_path: string;
    creation_time: string;
    modification_time: string;
};

export type ProjectCreateRequest = {
    project_name: string;
    project_description?: string;
    /**
     * Unix-style path, e.g. "engineering/firmware". Empty = root level.
     */
    folder_path?: string;
};

export type ProjectUpdateRequest = {
    project_name?: string;
    project_description?: string;
    /**
     * Move the project to a different folder by supplying a new path. Omit to keep the current folder.
     *
     */
    folder_path?: string;
};

export type Element = {
    element_identifier: string;
    project_identifier: string;
    element_type: ElementType;
    title: string;
    description?: string;
    content_sha: string;
    creation_time: string;
    modification_time: string;
    interest_level?: number;
    /**
     * Computed from child task progress. Only present for features.
     */
    readonly feature_progress?: number;
    assignee_identifier?: string;
    task_status?: TaskStatus;
    task_progress?: number;
    readonly close_time?: string;
    parent_feature_identifier?: string;
    start_phase_identifier?: string;
    delivery_phase_identifier?: string;
    custom_field_values?: Array<CustomFieldValue>;
    supervisors?: Array<string>;
    clients?: Array<ContactInfo>;
};

export type ElementCreateRequest = {
    element_type: ElementType;
    title: string;
    description?: string;
    interest_level?: number;
    assignee_identifier?: string;
    task_status?: TaskStatus;
    task_progress?: number;
    parent_feature_identifier?: string;
    start_phase_identifier?: string;
    delivery_phase_identifier?: string;
    supervisors?: Array<string>;
    clients?: Array<ContactInfo>;
};

export type ElementUpdateRequest = {
    title?: string;
    description?: string;
    interest_level?: number;
    assignee_identifier?: string;
    task_status?: TaskStatus;
    task_progress?: number;
    parent_feature_identifier?: string;
    start_phase_identifier?: string;
    delivery_phase_identifier?: string;
    supervisors?: Array<string>;
    clients?: Array<ContactInfo>;
};

export type ElementListResponse = {
    items: Array<Element>;
    /**
     * Total number of matching elements (before pagination)
     */
    total_count: number;
};

export type ContactInfo = {
    contact_name: string;
    contact_email?: string;
    contact_notes?: string;
};

export type ElementLink = {
    link_identifier: string;
    source_element_identifier: string;
    destination_element_identifier: string;
    link_type: LinkType;
    creation_time: string;
};

export type ElementLinkCreateRequest = {
    destination_element_identifier: string;
    link_type: LinkType;
};

export type ElementVersion = {
    version_identifier: string;
    element_identifier: string;
    version_number: number;
    content_sha: string;
    committed_time: string;
    committed_by_identifier?: string;
    commit_message?: string;
};

export type ElementVersionPatch = {
    version_identifier: string;
    forward_patch: Array<PatchOperation>;
    reverse_patch: Array<PatchOperation>;
};

export type PatchOperation = {
    op: 'add' | 'remove' | 'replace' | 'move' | 'copy' | 'test';
    /**
     * JSON Pointer (RFC 6901)
     */
    path: string;
    value?: unknown;
    from?: string;
};

export type Attachment = {
    attachment_identifier: string;
    element_identifier: string;
    file_name: string;
    file_size_bytes: number;
    content_type: string;
    upload_time: string;
    uploaded_by_identifier?: string;
};

export type CustomFieldDefinition = {
    field_definition_identifier: string;
    project_identifier: string;
    /**
     * Element type name, or "*" for all types
     */
    applicable_element_type: string;
    field_name: string;
    field_type: FieldType;
    /**
     * Type-specific options (choices list, min/max, default)
     */
    field_options?: {
        [key: string]: unknown;
    };
    display_order: number;
};

export type CustomFieldDefinitionCreateRequest = {
    applicable_element_type: string;
    field_name: string;
    field_type: FieldType;
    field_options?: {
        [key: string]: unknown;
    };
    display_order?: number;
};

export type CustomFieldDefinitionUpdateRequest = {
    field_name?: string;
    field_type?: FieldType;
    field_options?: {
        [key: string]: unknown;
    };
    display_order?: number;
};

export type CustomFieldValue = {
    field_definition_identifier: string;
    field_name: string;
    field_value: unknown;
};

export type CustomFieldValueSetRequest = {
    field_definition_identifier: string;
    field_value: unknown;
};

export type Phase = {
    phase_identifier: string;
    project_identifier: string;
    phase_name: string;
    phase_order: number;
    planned_start_date?: string;
    planned_end_date?: string;
};

export type PhaseCreateRequest = {
    phase_name: string;
    phase_order: number;
    planned_start_date?: string;
    planned_end_date?: string;
};

export type PhaseUpdateRequest = {
    phase_name?: string;
    phase_order?: number;
    planned_start_date?: string;
    planned_end_date?: string;
};

export type User = {
    user_identifier: string;
    email: string;
    display_name: string;
    external_identity_provider?: string;
};

export type Group = {
    group_identifier: string;
    group_name: string;
};

export type GroupProjectAccess = {
    group_identifier: string;
    project_identifier: string;
    access_level: AccessLevel;
};

export type ApiKeyInfo = {
    api_key_identifier: string;
    label: string;
    created_time: string;
    last_used_time?: string;
};

export type ApiKeyCreatedResponse = {
    api_key_identifier: string;
    label: string;
    /**
     * The raw API key, shown exactly once. Store it securely.
     */
    raw_key: string;
};

export type ElementWritable = {
    element_identifier: string;
    project_identifier: string;
    element_type: ElementType;
    title: string;
    description?: string;
    content_sha: string;
    creation_time: string;
    modification_time: string;
    interest_level?: number;
    assignee_identifier?: string;
    task_status?: TaskStatus;
    task_progress?: number;
    parent_feature_identifier?: string;
    start_phase_identifier?: string;
    delivery_phase_identifier?: string;
    custom_field_values?: Array<CustomFieldValue>;
    supervisors?: Array<string>;
    clients?: Array<ContactInfo>;
};

export type ElementListResponseWritable = {
    items: Array<ElementWritable>;
    /**
     * Total number of matching elements (before pagination)
     */
    total_count: number;
};

export type ProjectIdentifier = string;

export type ElementIdentifier = string;

export type Limit = number;

export type Offset = number;

export type AuthLoginData = {
    body?: never;
    path?: never;
    query?: {
        redirect_uri?: string;
    };
    url: '/auth/login';
};

export type AuthCallbackData = {
    body?: never;
    path?: never;
    query: {
        code: string;
        state: string;
    };
    url: '/auth/callback';
};

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Session cleared
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthGetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type AuthGetCurrentUserErrors = {
    /**
     * Authentication required
     */
    401: ErrorResponse;
};

export type AuthGetCurrentUserError = AuthGetCurrentUserErrors[keyof AuthGetCurrentUserErrors];

export type AuthGetCurrentUserResponses = {
    /**
     * Current user
     */
    200: User;
};

export type AuthGetCurrentUserResponse = AuthGetCurrentUserResponses[keyof AuthGetCurrentUserResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter to projects at or below this folder path (slash-delimited), e.g. "engineering/firmware". Returns projects whose folder_path equals the prefix or starts with "prefix/".
         *
         */
        folder_path_prefix?: string;
    };
    url: '/projects';
};

export type ListProjectsResponses = {
    /**
     * List of projects
     */
    200: {
        items: Array<Project>;
    };
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreateRequest;
    path?: never;
    query?: never;
    url: '/projects';
};

export type CreateProjectErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Created project
     */
    201: Project;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type ListProjectFoldersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/projects/folders';
};

export type ListProjectFoldersResponses = {
    /**
     * Sorted list of all folder paths
     */
    200: {
        folder_paths: Array<string>;
    };
};

export type ListProjectFoldersResponse = ListProjectFoldersResponses[keyof ListProjectFoldersResponses];

export type DeleteProjectData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}';
};

export type DeleteProjectErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteProjectError = DeleteProjectErrors[keyof DeleteProjectErrors];

export type DeleteProjectResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteProjectResponse = DeleteProjectResponses[keyof DeleteProjectResponses];

export type GetProjectData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}';
};

export type GetProjectErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetProjectError = GetProjectErrors[keyof GetProjectErrors];

export type GetProjectResponses = {
    /**
     * The project
     */
    200: Project;
};

export type GetProjectResponse = GetProjectResponses[keyof GetProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdateRequest;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}';
};

export type UpdateProjectErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Updated project
     */
    200: Project;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListElementsData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: {
        /**
         * Filter by element type(s), comma-separated
         */
        element_type?: Array<ElementType>;
        /**
         * Filter by task status(es), comma-separated
         */
        task_status?: Array<TaskStatus>;
        assignee_identifier?: string;
        /**
         * Full-text search query
         */
        search?: string;
        limit?: number;
        offset?: number;
    };
    url: '/projects/{project_identifier}/elements';
};

export type ListElementsResponses = {
    /**
     * Paginated list of elements
     */
    200: ElementListResponse;
};

export type ListElementsResponse = ListElementsResponses[keyof ListElementsResponses];

export type CreateElementData = {
    body: ElementCreateRequest;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/elements';
};

export type CreateElementErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type CreateElementError = CreateElementErrors[keyof CreateElementErrors];

export type CreateElementResponses = {
    /**
     * Created element
     */
    201: Element;
};

export type CreateElementResponse = CreateElementResponses[keyof CreateElementResponses];

export type DeleteElementData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}';
};

export type DeleteElementErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteElementError = DeleteElementErrors[keyof DeleteElementErrors];

export type DeleteElementResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteElementResponse = DeleteElementResponses[keyof DeleteElementResponses];

export type GetElementData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}';
};

export type GetElementErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetElementError = GetElementErrors[keyof GetElementErrors];

export type GetElementResponses = {
    /**
     * The element with custom fields, supervisors, and clients populated
     */
    200: Element;
};

export type GetElementResponse = GetElementResponses[keyof GetElementResponses];

export type UpdateElementData = {
    body: ElementUpdateRequest;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}';
};

export type UpdateElementErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateElementError = UpdateElementErrors[keyof UpdateElementErrors];

export type UpdateElementResponses = {
    /**
     * Updated element
     */
    200: Element;
};

export type UpdateElementResponse = UpdateElementResponses[keyof UpdateElementResponses];

export type SearchElementsData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query: {
        query: string;
        limit?: number;
        offset?: number;
    };
    url: '/projects/{project_identifier}/elements/search';
};

export type SearchElementsResponses = {
    /**
     * Search results
     */
    200: ElementListResponse;
};

export type SearchElementsResponse = SearchElementsResponses[keyof SearchElementsResponses];

export type ListElementLinksData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: {
        direction?: 'outgoing' | 'incoming' | 'both';
    };
    url: '/elements/{element_identifier}/links';
};

export type ListElementLinksResponses = {
    /**
     * Links
     */
    200: {
        items: Array<ElementLink>;
    };
};

export type ListElementLinksResponse = ListElementLinksResponses[keyof ListElementLinksResponses];

export type CreateElementLinkData = {
    body: ElementLinkCreateRequest;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/links';
};

export type CreateElementLinkErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type CreateElementLinkError = CreateElementLinkErrors[keyof CreateElementLinkErrors];

export type CreateElementLinkResponses = {
    /**
     * Created link
     */
    201: ElementLink;
};

export type CreateElementLinkResponse = CreateElementLinkResponses[keyof CreateElementLinkResponses];

export type DeleteElementLinkData = {
    body?: never;
    path: {
        link_identifier: string;
    };
    query?: never;
    url: '/links/{link_identifier}';
};

export type DeleteElementLinkErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteElementLinkError = DeleteElementLinkErrors[keyof DeleteElementLinkErrors];

export type DeleteElementLinkResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteElementLinkResponse = DeleteElementLinkResponses[keyof DeleteElementLinkResponses];

export type ListElementVersionsData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/elements/{element_identifier}/versions';
};

export type ListElementVersionsResponses = {
    /**
     * Version history (newest first)
     */
    200: {
        items: Array<ElementVersion>;
    };
};

export type ListElementVersionsResponse = ListElementVersionsResponses[keyof ListElementVersionsResponses];

export type GetElementAtVersionData = {
    body?: never;
    path: {
        element_identifier: string;
        version_number: number;
    };
    query?: never;
    url: '/elements/{element_identifier}/versions/{version_number}';
};

export type GetElementAtVersionErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetElementAtVersionError = GetElementAtVersionErrors[keyof GetElementAtVersionErrors];

export type GetElementAtVersionResponses = {
    /**
     * Element state at the requested version
     */
    200: Element;
};

export type GetElementAtVersionResponse = GetElementAtVersionResponses[keyof GetElementAtVersionResponses];

export type GetElementVersionDiffData = {
    body?: never;
    path: {
        element_identifier: string;
        version_number: number;
    };
    query?: never;
    url: '/elements/{element_identifier}/versions/{version_number}/diff';
};

export type GetElementVersionDiffErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetElementVersionDiffError = GetElementVersionDiffErrors[keyof GetElementVersionDiffErrors];

export type GetElementVersionDiffResponses = {
    /**
     * Forward and reverse patches for this version
     */
    200: ElementVersionPatch;
};

export type GetElementVersionDiffResponse = GetElementVersionDiffResponses[keyof GetElementVersionDiffResponses];

export type ListAttachmentsData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/attachments';
};

export type ListAttachmentsResponses = {
    /**
     * Attachments
     */
    200: {
        items: Array<Attachment>;
    };
};

export type ListAttachmentsResponse = ListAttachmentsResponses[keyof ListAttachmentsResponses];

export type UploadAttachmentData = {
    body: {
        file: Blob | File;
    };
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/attachments';
};

export type UploadAttachmentErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type UploadAttachmentError = UploadAttachmentErrors[keyof UploadAttachmentErrors];

export type UploadAttachmentResponses = {
    /**
     * Created attachment metadata
     */
    201: Attachment;
};

export type UploadAttachmentResponse = UploadAttachmentResponses[keyof UploadAttachmentResponses];

export type DeleteAttachmentData = {
    body?: never;
    path: {
        attachment_identifier: string;
    };
    query?: never;
    url: '/attachments/{attachment_identifier}';
};

export type DeleteAttachmentErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type DeleteAttachmentError = DeleteAttachmentErrors[keyof DeleteAttachmentErrors];

export type DeleteAttachmentResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteAttachmentResponse = DeleteAttachmentResponses[keyof DeleteAttachmentResponses];

export type GetAttachmentDownloadUrlData = {
    body?: never;
    path: {
        attachment_identifier: string;
    };
    query?: never;
    url: '/attachments/{attachment_identifier}';
};

export type GetAttachmentDownloadUrlErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetAttachmentDownloadUrlError = GetAttachmentDownloadUrlErrors[keyof GetAttachmentDownloadUrlErrors];

export type GetAttachmentDownloadUrlResponses = {
    /**
     * Presigned URL
     */
    200: {
        download_url: string;
        expires_at: string;
    };
};

export type GetAttachmentDownloadUrlResponse = GetAttachmentDownloadUrlResponses[keyof GetAttachmentDownloadUrlResponses];

export type ListCustomFieldDefinitionsData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: {
        /**
         * Filter by applicable element type (or "*" for all)
         */
        element_type?: string;
    };
    url: '/projects/{project_identifier}/custom-field-definitions';
};

export type ListCustomFieldDefinitionsResponses = {
    /**
     * Custom field definitions
     */
    200: {
        items: Array<CustomFieldDefinition>;
    };
};

export type ListCustomFieldDefinitionsResponse = ListCustomFieldDefinitionsResponses[keyof ListCustomFieldDefinitionsResponses];

export type CreateCustomFieldDefinitionData = {
    body: CustomFieldDefinitionCreateRequest;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/custom-field-definitions';
};

export type CreateCustomFieldDefinitionErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type CreateCustomFieldDefinitionError = CreateCustomFieldDefinitionErrors[keyof CreateCustomFieldDefinitionErrors];

export type CreateCustomFieldDefinitionResponses = {
    /**
     * Created definition
     */
    201: CustomFieldDefinition;
};

export type CreateCustomFieldDefinitionResponse = CreateCustomFieldDefinitionResponses[keyof CreateCustomFieldDefinitionResponses];

export type DeleteCustomFieldDefinitionData = {
    body?: never;
    path: {
        field_definition_identifier: string;
    };
    query?: never;
    url: '/custom-field-definitions/{field_definition_identifier}';
};

export type DeleteCustomFieldDefinitionResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteCustomFieldDefinitionResponse = DeleteCustomFieldDefinitionResponses[keyof DeleteCustomFieldDefinitionResponses];

export type UpdateCustomFieldDefinitionData = {
    body: CustomFieldDefinitionUpdateRequest;
    path: {
        field_definition_identifier: string;
    };
    query?: never;
    url: '/custom-field-definitions/{field_definition_identifier}';
};

export type UpdateCustomFieldDefinitionResponses = {
    /**
     * Updated definition
     */
    200: CustomFieldDefinition;
};

export type UpdateCustomFieldDefinitionResponse = UpdateCustomFieldDefinitionResponses[keyof UpdateCustomFieldDefinitionResponses];

export type GetCustomFieldValuesData = {
    body?: never;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/custom-field-values';
};

export type GetCustomFieldValuesResponses = {
    /**
     * Custom field values
     */
    200: {
        items: Array<CustomFieldValue>;
    };
};

export type GetCustomFieldValuesResponse = GetCustomFieldValuesResponses[keyof GetCustomFieldValuesResponses];

export type SetCustomFieldValueData = {
    body: CustomFieldValueSetRequest;
    path: {
        element_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/custom-field-values';
};

export type SetCustomFieldValueErrors = {
    /**
     * Invalid request
     */
    400: ErrorResponse;
};

export type SetCustomFieldValueError = SetCustomFieldValueErrors[keyof SetCustomFieldValueErrors];

export type SetCustomFieldValueResponses = {
    /**
     * Value set
     */
    200: unknown;
};

export type DeleteCustomFieldValueData = {
    body?: never;
    path: {
        element_identifier: string;
        field_definition_identifier: string;
    };
    query?: never;
    url: '/elements/{element_identifier}/custom-field-values/{field_definition_identifier}';
};

export type DeleteCustomFieldValueResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteCustomFieldValueResponse = DeleteCustomFieldValueResponses[keyof DeleteCustomFieldValueResponses];

export type ListPhasesData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/phases';
};

export type ListPhasesResponses = {
    /**
     * Phases
     */
    200: {
        items: Array<Phase>;
    };
};

export type ListPhasesResponse = ListPhasesResponses[keyof ListPhasesResponses];

export type CreatePhaseData = {
    body: PhaseCreateRequest;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/phases';
};

export type CreatePhaseResponses = {
    /**
     * Created phase
     */
    201: Phase;
};

export type CreatePhaseResponse = CreatePhaseResponses[keyof CreatePhaseResponses];

export type DeletePhaseData = {
    body?: never;
    path: {
        phase_identifier: string;
    };
    query?: never;
    url: '/phases/{phase_identifier}';
};

export type DeletePhaseResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeletePhaseResponse = DeletePhaseResponses[keyof DeletePhaseResponses];

export type UpdatePhaseData = {
    body: PhaseUpdateRequest;
    path: {
        phase_identifier: string;
    };
    query?: never;
    url: '/phases/{phase_identifier}';
};

export type UpdatePhaseResponses = {
    /**
     * Updated phase
     */
    200: Phase;
};

export type UpdatePhaseResponse = UpdatePhaseResponses[keyof UpdatePhaseResponses];

export type ListUsersData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/users';
};

export type ListUsersResponses = {
    /**
     * Users
     */
    200: {
        items: Array<User>;
    };
};

export type ListUsersResponse = ListUsersResponses[keyof ListUsersResponses];

export type GetUserData = {
    body?: never;
    path: {
        user_identifier: string;
    };
    query?: never;
    url: '/users/{user_identifier}';
};

export type GetUserErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * The user
     */
    200: User;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type UpdateUserData = {
    body: {
        display_name?: string;
    };
    path: {
        user_identifier: string;
    };
    query?: never;
    url: '/users/{user_identifier}';
};

export type UpdateUserErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type UpdateUserError = UpdateUserErrors[keyof UpdateUserErrors];

export type UpdateUserResponses = {
    /**
     * Updated user
     */
    200: User;
};

export type UpdateUserResponse = UpdateUserResponses[keyof UpdateUserResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type ListGroupsResponses = {
    /**
     * Groups
     */
    200: {
        items: Array<Group>;
    };
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type CreateGroupData = {
    body: {
        group_name: string;
    };
    path?: never;
    query?: never;
    url: '/groups';
};

export type CreateGroupResponses = {
    /**
     * Created group
     */
    201: Group;
};

export type CreateGroupResponse = CreateGroupResponses[keyof CreateGroupResponses];

export type DeleteGroupData = {
    body?: never;
    path: {
        group_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}';
};

export type DeleteGroupResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteGroupResponse = DeleteGroupResponses[keyof DeleteGroupResponses];

export type GetGroupData = {
    body?: never;
    path: {
        group_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}';
};

export type GetGroupErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetGroupError = GetGroupErrors[keyof GetGroupErrors];

export type GetGroupResponses = {
    /**
     * The group
     */
    200: Group;
};

export type GetGroupResponse = GetGroupResponses[keyof GetGroupResponses];

export type ListGroupMembersData = {
    body?: never;
    path: {
        group_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}/members';
};

export type ListGroupMembersResponses = {
    /**
     * Group members
     */
    200: {
        items: Array<User>;
    };
};

export type ListGroupMembersResponse = ListGroupMembersResponses[keyof ListGroupMembersResponses];

export type AddGroupMemberData = {
    body: {
        user_identifier: string;
    };
    path: {
        group_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}/members';
};

export type AddGroupMemberResponses = {
    /**
     * Added
     */
    204: void;
};

export type AddGroupMemberResponse = AddGroupMemberResponses[keyof AddGroupMemberResponses];

export type RemoveGroupMemberData = {
    body?: never;
    path: {
        group_identifier: string;
        user_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}/members/{user_identifier}';
};

export type RemoveGroupMemberResponses = {
    /**
     * Removed
     */
    204: void;
};

export type RemoveGroupMemberResponse = RemoveGroupMemberResponses[keyof RemoveGroupMemberResponses];

export type ListUserGroupsData = {
    body?: never;
    path: {
        user_identifier: string;
    };
    query?: never;
    url: '/users/{user_identifier}/groups';
};

export type ListUserGroupsResponses = {
    /**
     * Groups
     */
    200: {
        items: Array<Group>;
    };
};

export type ListUserGroupsResponse = ListUserGroupsResponses[keyof ListUserGroupsResponses];

export type ListProjectAccessData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/access';
};

export type ListProjectAccessResponses = {
    /**
     * Access entries
     */
    200: {
        items: Array<GroupProjectAccess>;
    };
};

export type ListProjectAccessResponse = ListProjectAccessResponses[keyof ListProjectAccessResponses];

export type SetProjectAccessData = {
    body: GroupProjectAccess;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/access';
};

export type SetProjectAccessResponses = {
    /**
     * Access set
     */
    200: unknown;
};

export type RemoveProjectAccessData = {
    body?: never;
    path: {
        project_identifier: string;
        group_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/access/{group_identifier}';
};

export type RemoveProjectAccessResponses = {
    /**
     * Removed
     */
    204: void;
};

export type RemoveProjectAccessResponse = RemoveProjectAccessResponses[keyof RemoveProjectAccessResponses];

export type ListGroupAccessData = {
    body?: never;
    path: {
        group_identifier: string;
    };
    query?: never;
    url: '/groups/{group_identifier}/access';
};

export type ListGroupAccessResponses = {
    /**
     * Access entries for this group
     */
    200: {
        items: Array<GroupProjectAccess>;
    };
};

export type ListGroupAccessResponse = ListGroupAccessResponses[keyof ListGroupAccessResponses];

export type GetUserAccessLevelData = {
    body?: never;
    path: {
        project_identifier: string;
    };
    query?: never;
    url: '/projects/{project_identifier}/access/check';
};

export type GetUserAccessLevelErrors = {
    /**
     * Resource not found
     */
    404: ErrorResponse;
};

export type GetUserAccessLevelError = GetUserAccessLevelErrors[keyof GetUserAccessLevelErrors];

export type GetUserAccessLevelResponses = {
    /**
     * The user's effective access level
     */
    200: {
        access_level: AccessLevel;
    };
};

export type GetUserAccessLevelResponse = GetUserAccessLevelResponses[keyof GetUserAccessLevelResponses];

export type ListApiKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type ListApiKeysResponses = {
    /**
     * API keys (hashed_key is never returned)
     */
    200: {
        items: Array<ApiKeyInfo>;
    };
};

export type ListApiKeysResponse = ListApiKeysResponses[keyof ListApiKeysResponses];

export type CreateApiKeyData = {
    body: {
        label: string;
    };
    path?: never;
    query?: never;
    url: '/api-keys';
};

export type CreateApiKeyResponses = {
    /**
     * Created API key with raw key shown once
     */
    201: ApiKeyCreatedResponse;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        api_key_identifier: string;
    };
    query?: never;
    url: '/api-keys/{api_key_identifier}';
};

export type DeleteApiKeyResponses = {
    /**
     * Revoked
     */
    204: void;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];
